package main

import "github.com/breml/logstash-config/ast"

// knownPlugins lists official Logstash plugin names per section type.
// Source: Elastic's plugins-metadata.json (curated).
var knownPlugins = map[ast.PluginType]map[string]bool{
	ast.Input: {
		"azure_event_hubs": true,
		"beats":            true,
		"cloudwatch":       true,
		"couchdb_changes":  true,
		"dead_letter_queue": true,
		"elastic_agent":    true,
		"elasticsearch":    true,
		"exec":             true,
		"file":             true,
		"ganglia":          true,
		"gelf":             true,
		"generator":        true,
		"github":           true,
		"google_cloud_storage": true,
		"google_pubsub":    true,
		"graphite":         true,
		"heartbeat":        true,
		"http":             true,
		"http_poller":      true,
		"imap":             true,
		"irc":              true,
		"java_generator":   true,
		"java_stdin":       true,
		"jdbc":             true,
		"jms":              true,
		"jmx":              true,
		"kafka":            true,
		"kinesis":          true,
		"log4j":            true,
		"lumberjack":       true,
		"meetup":           true,
		"pipe":             true,
		"puppet_facter":    true,
		"rabbitmq":         true,
		"redis":            true,
		"relp":             true,
		"rss":              true,
		"s3":               true,
		"s3_sns_sqs":       true,
		"salesforce":       true,
		"snmp":             true,
		"snmptrap":         true,
		"sqs":              true,
		"stdin":            true,
		"stomp":            true,
		"syslog":           true,
		"tcp":              true,
		"twitter":          true,
		"udp":              true,
		"unix":             true,
		"varnishlog":       true,
		"websocket":        true,
		"wmi":              true,
		"xmpp":             true,
	},
	ast.Filter: {
		"age":              true,
		"aggregate":        true,
		"alter":            true,
		"bytes":            true,
		"cidr":             true,
		"cipher":           true,
		"clone":            true,
		"csv":              true,
		"date":             true,
		"de_dot":           true,
		"dissect":          true,
		"dns":              true,
		"drop":             true,
		"elapsed":          true,
		"elastic_integration": true,
		"elasticsearch":    true,
		"environment":      true,
		"extractnumbers":   true,
		"fingerprint":      true,
		"geoip":            true,
		"grok":             true,
		"http":             true,
		"i18n":             true,
		"java_uuid":        true,
		"json":             true,
		"json_encode":      true,
		"kv":               true,
		"memcached":        true,
		"metricize":        true,
		"metrics":          true,
		"mutate":           true,
		"prune":            true,
		"range":            true,
		"ruby":             true,
		"sleep":            true,
		"split":            true,
		"syslog_pri":       true,
		"throttle":         true,
		"tld":              true,
		"translate":        true,
		"truncate":         true,
		"urldecode":        true,
		"useragent":        true,
		"uuid":             true,
		"xml":              true,
	},
	ast.Output: {
		"boundary":         true,
		"circonus":         true,
		"cloudwatch":       true,
		"csv":              true,
		"datadog":          true,
		"datadog_metrics":  true,
		"elastic_app_search": true,
		"elasticsearch":    true,
		"email":            true,
		"exec":             true,
		"file":             true,
		"ganglia":          true,
		"gelf":             true,
		"google_bigquery":  true,
		"google_cloud_storage": true,
		"google_pubsub":    true,
		"graphite":         true,
		"graphtastic":      true,
		"http":             true,
		"influxdb":         true,
		"irc":              true,
		"java_stdout":      true,
		"juggernaut":       true,
		"kafka":            true,
		"librato":          true,
		"loggly":           true,
		"lumberjack":       true,
		"metriccatcher":    true,
		"mongodb":          true,
		"nagios":           true,
		"nagios_nsca":      true,
		"opentsdb":         true,
		"pagerduty":        true,
		"pipe":             true,
		"rabbitmq":         true,
		"redis":            true,
		"redmine":          true,
		"riak":             true,
		"riemann":          true,
		"s3":               true,
		"sink":             true,
		"sns":              true,
		"solr_http":        true,
		"sqs":              true,
		"statsd":           true,
		"stdout":           true,
		"stomp":            true,
		"syslog":           true,
		"tcp":              true,
		"timber":           true,
		"udp":              true,
		"webhdfs":          true,
		"websocket":        true,
		"xmpp":             true,
		"zabbix":           true,
	},
}

// knownCodecs lists official Logstash codec plugin names.
var knownCodecs = map[string]bool{
	"avro":          true,
	"cef":           true,
	"cloudfront":    true,
	"cloudtrail":    true,
	"collectd":      true,
	"compress_spooler": true,
	"dots":          true,
	"edn":           true,
	"edn_lines":     true,
	"es_bulk":       true,
	"fluent":        true,
	"graphite":      true,
	"gzip_lines":    true,
	"java_line":     true,
	"java_plain":    true,
	"json":          true,
	"json_lines":    true,
	"line":          true,
	"msgpack":       true,
	"multiline":     true,
	"netflow":       true,
	"nmap":          true,
	"oldlogstashjson": true,
	"plain":         true,
	"protobuf":      true,
	"rubydebug":     true,
}

// commonOptions are options available on all plugins of a given type.
var commonOptions = map[ast.PluginType]map[string]bool{
	ast.Input: {
		"id":            true,
		"enable_metric": true,
		"codec":         true,
		"type":          true,
		"tags":          true,
		"add_field":     true,
	},
	ast.Filter: {
		"id":             true,
		"enable_metric":  true,
		"add_tag":        true,
		"remove_tag":     true,
		"add_field":      true,
		"remove_field":   true,
		"periodic_flush": true,
	},
	ast.Output: {
		"id":            true,
		"enable_metric": true,
		"codec":         true,
		"workers":       true,
	},
}

// pluginOptions maps plugin names to their specific accepted options.
// Only the most commonly used plugins are included.
var pluginOptions = map[string]map[string]bool{
	// --- Input plugins ---
	"beats": {
		"port": true, "host": true, "ssl": true, "ssl_certificate": true,
		"ssl_key": true, "ssl_certificate_authorities": true,
		"ssl_enabled": true, "ssl_client_authentication": true,
		"client_inactivity_timeout": true, "include_codec_tag": true,
		"tls_min_version": true, "tls_max_version": true, "cipher_suites": true,
		"enrich": true, "executor_threads": true, "ecs_compatibility": true,
	},
	"file": {
		"path": true, "exclude": true, "sincedb_path": true,
		"sincedb_write_interval": true, "start_position": true,
		"stat_interval": true, "discover_interval": true,
		"close_older": true, "ignore_older": true, "delimiter": true,
		"mode": true, "file_completed_action": true, "file_completed_log_path": true,
		"file_chunk_count": true, "file_chunk_size": true, "file_sort_by": true,
		"file_sort_direction": true, "max_open_files": true, "exit_after_read": true,
		"ecs_compatibility": true,
	},
	"kafka": {
		"bootstrap_servers": true, "topics": true, "topics_pattern": true,
		"group_id": true, "client_id": true, "consumer_threads": true,
		"auto_offset_reset": true, "auto_commit_interval_ms": true,
		"decorate_events": true, "key_deserializer_class": true,
		"value_deserializer_class": true, "schema_registry_url": true,
		"max_poll_records": true, "max_poll_interval_ms": true,
		"session_timeout_ms": true, "heartbeat_interval_ms": true,
		"request_timeout_ms": true, "fetch_max_bytes": true,
		"fetch_max_wait_ms": true, "fetch_min_bytes": true,
		"max_partition_fetch_bytes": true, "partition_assignment_strategy": true,
		"sasl_mechanism": true, "sasl_jaas_config": true, "sasl_kerberos_service_name": true,
		"security_protocol": true, "ssl_truststore_location": true,
		"ssl_truststore_password": true, "ssl_truststore_type": true,
		"ssl_keystore_location": true, "ssl_keystore_password": true,
		"ssl_keystore_type": true, "ssl_key_password": true,
		"ssl_endpoint_identification_algorithm": true,
		"check_crcs": true, "connections_max_idle_ms": true,
		"metadata_max_age_ms": true, "receive_buffer_bytes": true,
		"reconnect_backoff_ms": true, "retry_backoff_ms": true,
		"send_buffer_bytes": true, "isolation_level": true,
		"poll_timeout_ms": true, "ecs_compatibility": true,
	},
	"jdbc": {
		"jdbc_connection_string": true, "jdbc_driver_class": true,
		"jdbc_driver_library": true, "jdbc_user": true, "jdbc_password": true,
		"jdbc_paging_enabled": true, "jdbc_page_size": true,
		"jdbc_fetch_size": true, "jdbc_validation_timeout": true,
		"jdbc_pool_timeout": true, "jdbc_default_timezone": true,
		"statement": true, "statement_filepath": true, "parameters": true,
		"schedule": true, "clean_run": true, "record_last_run": true,
		"use_column_value": true, "tracking_column": true,
		"tracking_column_type": true, "last_run_metadata_path": true,
		"lowercase_column_names": true, "connection_retry_attempts": true,
		"connection_retry_attempts_wait_time": true, "sequel_opts": true,
		"columns_charset": true, "ecs_compatibility": true, "prepared_statement_bind_values": true,
		"prepared_statement_name": true, "target": true,
	},
	"http": {
		"host": true, "port": true, "user": true, "password": true,
		"additional_codecs": true, "cipher_suites": true,
		"max_content_length": true, "max_pending_requests": true,
		"response_headers": true, "remote_host_target_field": true,
		"request_headers_target_field": true, "ssl_certificate": true,
		"ssl_certificate_authorities": true, "ssl_enabled": true,
		"ssl_handshake_timeout": true, "ssl_key": true,
		"ssl_key_passphrase": true, "ssl_client_authentication": true,
		"threads": true, "tls_max_version": true, "tls_min_version": true,
		"ecs_compatibility": true,
	},
	"http_poller": {
		"urls": true, "schedule": true, "request_timeout": true,
		"socket_timeout": true, "connect_timeout": true,
		"automatic_retries": true, "cacert": true, "client_cert": true,
		"client_key": true, "cookies": true, "follow_redirects": true,
		"keepalive": true, "keystore": true, "keystore_password": true,
		"keystore_type": true, "metadata_target": true, "pool_max": true,
		"pool_max_per_route": true, "proxy": true, "retry_non_idempotent": true,
		"target": true, "truststore": true, "truststore_password": true,
		"truststore_type": true, "user": true, "password": true,
		"validate_after_inactivity": true, "ecs_compatibility": true,
	},
	"syslog": {
		"host": true, "port": true, "proxy_protocol": true,
		"timezone": true, "locale": true, "use_labels": true,
		"severity_labels": true, "facility_labels": true,
		"grok_pattern": true, "syslog_field": true,
		"ecs_compatibility": true,
	},
	"tcp": {
		"host": true, "port": true, "mode": true, "proxy_protocol": true,
		"ssl_cert": true, "ssl_certificate": true, "ssl_certificate_authorities": true,
		"ssl_enabled": true, "ssl_extra_chain_certs": true,
		"ssl_key": true, "ssl_key_passphrase": true, "ssl_client_authentication": true,
		"tcp_keep_alive": true, "dns_reverse_lookup_enabled": true,
		"ecs_compatibility": true,
	},
	"udp": {
		"host": true, "port": true, "buffer_size": true,
		"queue_size": true, "receive_buffer_bytes": true,
		"workers": true, "source_ip_fieldname": true,
		"ecs_compatibility": true,
	},
	"s3": {
		"bucket": true, "region": true, "access_key_id": true,
		"secret_access_key": true, "session_token": true,
		"prefix": true, "additional_settings": true,
		"aws_credentials_file": true, "backup_add_prefix": true,
		"backup_to_bucket": true, "backup_to_dir": true,
		"delete": true, "endpoint": true, "exclude_pattern": true,
		"include_object_properties": true, "interval": true,
		"proxy_uri": true, "role_arn": true, "role_session_name": true,
		"sincedb_path": true, "temporary_directory": true,
		"use_aws_bundled_ca": true, "watch_for_new_files": true,
		"ecs_compatibility": true,
	},
	"stdin": {
		"ecs_compatibility": true,
	},
	"generator": {
		"count": true, "lines": true, "message": true, "threads": true,
		"ecs_compatibility": true,
	},
	"rabbitmq": {
		"host": true, "port": true, "user": true, "password": true,
		"vhost": true, "queue": true, "exchange": true, "key": true,
		"exchange_type": true, "durable": true, "auto_delete": true,
		"exclusive": true, "passive": true, "prefetch_count": true,
		"ack": true, "arguments": true, "connect_retry_interval": true,
		"connection_timeout": true, "heartbeat": true, "ssl": true,
		"ssl_certificate_password": true, "ssl_certificate_path": true,
		"ssl_version": true, "subscription_retry_interval_seconds": true,
		"threads": true, "metadata_enabled": true, "ecs_compatibility": true,
	},
	"redis": {
		"host": true, "port": true, "db": true, "password": true,
		"data_type": true, "key": true, "batch_count": true,
		"threads": true, "timeout": true,
	},
	"elasticsearch": {
		"hosts": true, "index": true, "query": true, "search_api": true,
		"user": true, "password": true, "api_key": true,
		"cloud_auth": true, "cloud_id": true, "ca_trusted_fingerprint": true,
		"docinfo": true, "docinfo_fields": true, "docinfo_target": true,
		"ecs_compatibility": true, "response_type": true, "retries": true,
		"schedule": true, "scroll": true, "size": true, "slices": true,
		"ssl_certificate": true, "ssl_certificate_authorities": true,
		"ssl_enabled": true, "ssl_key": true, "ssl_keystore_password": true,
		"ssl_keystore_path": true, "ssl_truststore_password": true,
		"ssl_truststore_path": true, "ssl_verification_mode": true,
		"ssl_cipher_suites": true, "target": true, "proxy": true,
	},

	// --- Filter plugins ---
	"grok": {
		"match": true, "overwrite": true, "patterns_dir": true,
		"patterns_files_glob": true, "named_captures_only": true,
		"keep_empty_captures": true, "break_on_match": true,
		"tag_on_failure": true, "tag_on_timeout": true, "timeout_millis": true,
		"target": true, "timeout_scope": true, "ecs_compatibility": true,
	},
	"mutate": {
		"convert": true, "copy": true, "gsub": true, "join": true,
		"lowercase": true, "merge": true, "coerce": true,
		"rename": true, "replace": true, "split": true,
		"strip": true, "update": true, "uppercase": true,
		"capitalize": true, "tag_on_failure": true,
	},
	"date": {
		"match": true, "target": true, "locale": true, "timezone": true,
		"tag_on_failure": true, "ecs_compatibility": true,
	},
	"geoip": {
		"source": true, "target": true, "database": true, "fields": true,
		"cache_size": true, "default_database_type": true,
		"tag_on_failure": true, "ecs_compatibility": true,
	},
	"kv": {
		"source": true, "target": true, "field_split": true,
		"value_split": true, "field_split_pattern": true,
		"value_split_pattern": true, "prefix": true, "transform_key": true,
		"transform_value": true, "include_keys": true, "exclude_keys": true,
		"include_brackets": true, "recursive": true, "allow_duplicate_values": true,
		"allow_empty_values": true, "default_keys": true,
		"trim_key": true, "trim_value": true, "trimkey": true, "trimvalue": true,
		"tag_on_failure": true, "tag_on_timeout": true, "timeout_millis": true,
		"whitespace": true, "ecs_compatibility": true,
	},
	"dissect": {
		"mapping": true, "convert_datatype": true,
		"tag_on_failure": true,
	},
	"json": {
		"source": true, "target": true, "skip_on_invalid_json": true,
		"tag_on_failure": true, "ecs_compatibility": true,
	},
	"csv": {
		"source": true, "columns": true, "separator": true,
		"quote_char": true, "convert": true, "autodetect_column_names": true,
		"autogenerate_column_names": true, "skip_empty_columns": true,
		"skip_empty_rows": true, "skip_header": true, "target": true,
		"ecs_compatibility": true,
	},
	"ruby": {
		"code": true, "init": true, "path": true,
		"script_params": true, "tag_on_exception": true,
	},
	"useragent": {
		"source": true, "target": true, "regexes": true, "prefix": true,
		"lru_cache_size": true, "ecs_compatibility": true,
	},
	"translate": {
		"source": true, "target": true, "dictionary": true,
		"dictionary_path": true, "exact": true, "regex": true,
		"fallback": true, "field": true, "destination": true,
		"override": true, "refresh_interval": true,
		"refresh_behaviour": true, "iterate_on": true,
		"ecs_compatibility": true,
	},
	"xml": {
		"source": true, "target": true, "store_xml": true,
		"xpath": true, "namespaces": true, "remove_namespaces": true,
		"force_array": true, "force_content": true,
		"suppress_empty": true, "parse_options": true,
		"ecs_compatibility": true,
	},
	"fingerprint": {
		"source": true, "target": true, "method": true, "key": true,
		"base64encode": true, "concatenate_sources": true,
		"concatenate_all_fields": true, "ecs_compatibility": true,
	},
	"drop": {},
	"clone": {
		"clones": true, "ecs_compatibility": true,
	},
	"dns": {
		"resolve": true, "reverse": true, "action": true,
		"nameserver": true, "timeout": true, "max_retries": true,
		"hit_cache_size": true, "hit_cache_ttl": true,
		"failed_cache_size": true, "failed_cache_ttl": true,
		"hostsfile": true, "ecs_compatibility": true,
	},
	"cidr": {
		"address": true, "network": true, "separator": true,
	},
	"aggregate": {
		"task_id": true, "code": true, "map_action": true,
		"end_of_task": true, "timeout": true, "timeout_code": true,
		"push_map_as_event_on_timeout": true, "push_previous_map_as_event": true,
		"timeout_task_id_field": true, "timeout_tags": true,
		"inactivity_timeout": true, "aggregate_maps_path": true,
	},
	"elapsed": {
		"start_tag": true, "end_tag": true, "unique_id_field": true,
		"timeout": true, "new_event_on_match": true,
	},
	"throttle": {
		"before_count": true, "after_count": true, "period": true,
		"max_age": true, "key": true,
	},
	"urldecode": {
		"field": true, "all_fields": true, "charset": true,
		"tag_on_failure": true,
	},
	"split": {
		"field": true, "target": true, "terminator": true,
	},
	"prune": {
		"whitelist_names": true, "blacklist_names": true,
		"whitelist_values": true, "blacklist_values": true,
		"interpolate": true,
	},
	"json_encode": {
		"source": true, "target": true,
	},

	// --- Output plugins ---
	// "elasticsearch" already defined above (shared name with input)
	// We use a flat map so the same key works for both.
	"stdout": {
		"ecs_compatibility": true,
	},
	"email": {
		"to": true, "from": true, "subject": true, "body": true,
		"htmlbody": true, "cc": true, "bcc": true, "replyto": true,
		"contenttype": true, "address": true, "port": true,
		"domain": true, "username": true, "password": true,
		"authentication": true, "use_tls": true, "debug": true,
		"via": true, "attachments": true, "template_file": true,
	},
	"s3_output": {}, // s3 already exists for input
}

// getPluginOptions returns the set of known options for a plugin.
// It merges common options for the section type with plugin-specific options.
// Returns nil if the plugin is unknown (no option checking should be done).
func getPluginOptions(pluginType ast.PluginType, pluginName string) map[string]bool {
	// Check if plugin is known at all
	if plugins, ok := knownPlugins[pluginType]; ok {
		if !plugins[pluginName] {
			return nil // unknown plugin, skip option checking
		}
	}

	common := commonOptions[pluginType]
	specific := pluginOptions[pluginName]

	// If we have no specific schema, only check common options
	if specific == nil {
		return common
	}

	merged := make(map[string]bool, len(common)+len(specific))
	for k := range common {
		merged[k] = true
	}
	for k := range specific {
		merged[k] = true
	}
	return merged
}
